[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"


[project]
name = "{{ cookiecutter.project_slug }}"
description = "{{ cookiecutter.project_short_description }}"
authors = [
  { name = "{{ cookiecutter.author_full_name }}", email = "{{ cookiecutter.author_email }}" },
]
{% if cookiecutter.project_layout == "src" -%}
packages = [
  {include = "{{ cookiecutter.package_slug }}", from="src"},
]
{% else -%}
packages = [
  {include = "{{ cookiecutter.package_slug }}"},
]
{% endif -%}
readme = "README.md"
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
{%- if cookiecutter.project_license == "MIT" %}
  "License :: OSI Approved :: MIT License",
{%- elif cookiecutter.project_license == "BSD 3 Clause" %}
  "License :: OSI Approved :: BSD License",
{%- elif cookiecutter.project_license == "Apache Software License 2.0" %}
  "License :: OSI Approved :: Apache Software License",
{%- elif cookiecutter.project_license == "GNU General Public License v3" %}
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
{%- endif %}
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering",
{%- if cookiecutter.use_mypy == "yes" -%}
  "Typing :: Typed",
{% endif %}
]
dynamic = ["version"]
requires-python = ">=3.8.1,<4"
dependencies = [
{# keep this line here #}
{%- if cookiecutter.use_pytest == "yes" -%}
    "pytest>=7.3.2",
{% if cookiecutter.use_coverage == "yes" -%}
    "pytest-cov>=4.1.0",
{% endif %}
{%- endif -%}{#- end of use_pytest -#}
{%- if cookiecutter.use_hypothesis == "yes" -%}
    "hypothesis>=6.0",
{% endif %}
{%- if cookiecutter.use_coverage == "yes" -%}
    "coverage>=7.2.7",
{% endif %}
{%- if cookiecutter.use_black == "yes" -%}
    "black>=23.3.0,<23.10",
{% endif %}
{%- if cookiecutter.use_isort == "yes" -%}
    "isort>=5.12.0",
{% endif %}
{%- if cookiecutter.use_pre_commit -%}
    "pre-commit>=3.3.2",
{% endif %}
{%- if cookiecutter.use_flake8 == "yes" -%}
    "flake8>=4.0.1, <7",
{% endif %}
{%- if cookiecutter.use_ruff == "yes" -%}
    "ruff>=0.2.0",
{% endif %}
{%- if cookiecutter.use_mypy == "yes" -%}
    "mypy>=1.5.0",
{% endif %}
{%- if cookiecutter.use_bandit == "yes" -%}
    "bandit>=1.7.5",
{% endif %}
{%- if cookiecutter.use_pydocstyle == "yes" -%}
    "pydocstyle>=6.3.0",
{% endif %}
{%- if cookiecutter.use_vulture == "yes" -%}
    "vulture>=2.7",
{% endif %}
{%- if cookiecutter.use_mccabe == "yes" -%}
    "mccabe>=0.6.1",
{% endif %}
{%- if cookiecutter.use_containers in ['Docker', 'Podman'] -%}
# if you want to use docker-compose from your system, remove compose-go here
    "compose-go>=2.18.1",
{% endif %}
    "ipython<8",
    "ipykernel>=6.0.0",
{%- if cookiecutter.documentation_engine == 'mkdocs' -%}
    "Jinja2>=3.1.2",
    "mkdocs>=1.4.3",
    "mkdocs-exclude>=1.0.2",
    "mkdocs-jupyter>=0.24.1",
    "mkdocs-literate-nav>=0.6.0",
    "mkdocs-macros-plugin>=0.7.0, <1",
    "mkdocs-material>=9.1.15",
    "mkdocstrings>=0.21.2",
    "mkdocstrings-python>=1.1.2",
{% elif cookiecutter.documentation_engine == 'sphinx' -%}
    "Sphinx>=6.2.1",
    "sphinx-rtd-theme>=1.2.2",
    "importlib-metadata>=6.5.1",
    "myst-parser>=0.19.2",
    "nbsphinx>=0.9.2",
    "pandoc>=2.3",
{% elif cookiecutter.documentation_engine == 'jupyter-book' -%}
    "jupyter-book>=0.15.1",
    "myst-parser>=0.18.1",
{% endif %}
{%- if cookiecutter.use_makim == "yes" %}
    "makim >=1.12.0",
{% endif %}
]

[project.urls]
Homepage = "{{ cookiecutter.project_url }}"
"Bug Tracker" = "{{ cookiecutter.project_url }}/issues"
Discussions = "{{ cookiecutter.project_url }}/discussions"
Changelog = "{{ cookiecutter.project_url }}/releases"

[tool.maturin]
manifest-path = "Cargo.toml"


{% include "build-system/base-pyproject.toml" %}
{#- keep this line at the end of the file -#}
