# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹  Usage Questions
    url: https://github.com/osl-incubator/scicookie/discussions
    about: |
      Use Cookiecutter's GitHub Discussions to ask "How do I do X with Cookiecutter?".
  - name: ğŸ“–  Tutorial
    url: https://github.com/osl-incubator/scicookie
    about: |
      The Cookiecutter tutorial is continually updated and provides an in depth walkthrough
      of how to use the latest release of Cookiecutter.
  - name: ğŸ“  Cookiecutter Code of Conduct
    url: https://github.com/osl-incubator/scicookie/blob/main/CODE_OF_CONDUCT.md
    about: Expectations for how people will interact with each other on Cookiecutter's GitHub.
