# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: üôã  Usage Questions
  url: https://github.com/osl-incubator/cookiecutter-python/discussions
  about: |
    Use Cookiecutter's GitHub Discussions to ask "How do I do X with Cookiecutter?".
- name: üìñ  Tutorial
  url: https://github.com/osl-incubator/cookiecutter-python
  about: |
    The Cookiecutter tutorial is continually updated and provides an in depth walkthrough
    of how to use the latest release of Cookiecutter.
- name: üìù  Cookiecutter Code of Conduct
  url: https://github.com/osl-incubator/cookiecutter-python/blob/main/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on Cookiecutter's GitHub.

Thanks [Pyhf](https://github.com/scikit-hep/pyhf/tree/main/.github/ISSUE_TEMPLATE) for  for coming up with such detailed and great templates slightly_smiling_face
