{%- if cookiecutter.project_layout == "src" -%}
{%- set package_path = "src/" + cookiecutter.package_slug -%}
{%- else -%}
{%- set package_path = cookiecutter.package_slug -%}
{%- endif -%}
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
{# keep this comment #}
{%- if cookiecutter.use_prettier == "yes" %}
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
{% endif %}
  - repo: local
    hooks:
      # NOTE: This is a total unnecessary check, just used as part of the
      #       template. Remove this after creating the template.
      - id: check-python
        name: check-python
        entry: python --version
        language: system
        pass_filenames: no
{# keep this comment #}
{%- if cookiecutter.use_black == "yes" %}
      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_flake8 == "yes" %}
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_ruff == 'yes' %}
      - id: ruff
        name: ruff
        entry: ruff --fix
        language: system
        pass_filenames: true
        files: "./"
        types:
          - python
{% endif %}
{%- if cookiecutter.use_isort == "yes" %}
      - id: isort
        name: isort
        entry: isort
        language: system
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_mypy == "yes" %}
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: "{{ package_path }}"
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_shellcheck == "yes" %}
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types_or:
          - sh
          - shell
          - ash
          - bash
          - bats
          - dash
          - ksh
{% endif %}
{%- if cookiecutter.use_bandit == "yes" %}
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: ['--configfile', 'pyproject.toml', '-iii', '-lll']
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_pydocstyle == "yes" %}
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        files: "{{ package_path }}"
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_vulture == "yes" %}
      - id: vulture
        name: vulture
        entry: vulture
        language: system
        files: "{{ package_path }}"
        description: Find unused Python code.
        pass_filenames: true
        types:
          - python
{% endif %}
{%- if cookiecutter.use_mccabe == "yes" %}
      - id: mccabe
        name: mccabe
        entry: python -m mccabe --min 10
        language: system
        files: "{{ package_path }}"
        pass_filenames: true
        types:
          - python
{% endif %}
{#- keep this at the end of the file -#}
