# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: {{cookiecutter.project_name}}
author: {{cookiecutter.author_full_name}}
logo: ../images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: {{cookiecutter.project_slug}}.tex

# Information about where the book exists on the web
repository:
  url: {{cookiecutter.git_https_origin}}  # Online location of your book
  path_to_book: docs-jupyter-book  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
