# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: ğŸ™‹  Usage Questions
  url: https://github.com/{{cookiecutter.project_slug}}/discussions
  about: |
    Use {{ cookiecutter.project_name }}'s GitHub Discussions to ask "How do I do X with Cookiecutter?".
- name: ğŸ“–  Tutorial
  url: https://github.com/{{cookiecutter.project_slug}}
  about: |
    The {{ cookiecutter.project_name }} tutorial is continually updated and provides an in depth walkthrough
    of how to use the latest release of Cookiecutter.
- name: ğŸ“  {{ cookiecutter.project_name }} Code of Conduct
  url: https://github.com/{{cookiecutter.project_slug}}/coc/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on Cookiecutter's GitHub.
